name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Another Workflow
        env:
          MY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: ${{ github.repository }}
          event-type: trigger-workflow
          client-payload: '{"key": "value"}'
