name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:   
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Another Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow
          client-payload: '{"key": "value"}'
